server:
  port: 4000
spring:
  application:
    name: ms-bootcoin-customer-service
  #config:
  # import: optional:configserver:http://localhost:8888
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bootcoin
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
                                                      
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

kafka:
  topic:
    bootcoin:
      wallet:
        create:
          name: bootcoin-wallet-create
          
client:
  bank:
    account:
      url: http://localhost:8101/account
  bootcoin:
    wallet:
      url: http://localhost:4001/wallet